name: quickrider
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.0
  logger: ^2.2.0
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  equatable: ^2.0.7
  get_it: ^7.7.0
  connectivity_plus: ^5.0.2
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.2
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  flutter_localization: ^0.3.3
  flutter_otp_text_field: ^1.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl: ^0.20.2

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - lib/assets/svg/
    - lib/assets/images/
    - lib/assets/animations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: lib/assets/fonts/Tajawal-Regular.ttf
